{
 "title": "Hit count",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "paths", "query": "label_values(path)" }
  ]
 },
 "panels": [
  {
   "title": "runner",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{path=\"/run_cyber_dojo_sh\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ragger",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{path=\"/colour\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "differ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{path=\"/diff\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "starter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{path=\"/manifests\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "avatars",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{path=\"/names\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}